{% set name = "scrape-search-engine" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: c1d6093053e54558d1a883608285e143363512df123699647a5353ee6e068c27

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - bs4
    - requests
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - ScrapeSearchEngine

about:
  home: "https://github.com/sujitmandal/scrape-search-engine"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Search anything on the different Search Engine's it will collect all the links."
  doc_url: https://sujitmandal.github.io/scrape-search-engine/
  dev_url: https://github.com/sujitmandal/scrape-search-engine

extra:
  recipe-maintainers:
    - sujitmandal
